services:
  api:
    container_name: edis
    build:
      context: docker
      args:
        - WITH_XDEBUG=true
    env_file: .env
    stdin_open: true # equivalent of -i
    tty: true        # equivalent of -t
    volumes:
      - ./:/var/www/src
      - ./docker/php.ini:/usr/local/etc/php/php.ini
